### ISSUE TITLE
Layout - frontend site

### ISSUE THREAD

**Issue by Guilherme-Chinaglia** [doesangueorg/doesangueorg.github.io#3]
Hey @JoseCage , i was seeing the gulpfile.js from doesangue.org site, and i want to know if you have a layout image from the site? Or an ideia of how the site is gonna stay?

**Comment by JoseCage** [comment]
@Guilherme-Chinaglia Yes i have a basic (older) prototype i have created :point_down:

**Note**: the site is [doesangue.me](https://doesangue.me) not `.org`. I keep the site off because the repo is empty at moment (the domain is registered)..

![prototype](https://user-images.githubusercontent.com/4200487/29528672-c023b13e-8694-11e7-84f7-c0a5c45da37a.png)

**Comment by JoseCage** [comment]
> @JoseCage did you have a mobile prototype layout?

@Guilherme-Chinaglia i have created a repo for android app version. At this moment i think i have only designed a prototype for **signup steps**. 

* [android repo](https://github.com/doesangueorg/android)
